// Internationalization (i18n) support
// Supports both built-in translations and Chrome Extension i18n API

const i18n = {
  en: {
    // Header
    title: 'SearchHub',
    themeToggle: 'Toggle theme',
    compactMode: 'Compact mode',
    editMode: 'Edit mode',
    settings: 'Settings',

    // Search
    searchPlaceholder: 'Search anything across all engines...',
    search: 'Search',
    enginesSelected: 'engines selected',

    // Categories
    engines: 'engines',
    expand: 'Expand',
    collapse: 'Collapse',
    selectAll: 'Select all engines in this category',

    // Combos
    saveAsCombo: 'Save as combo',
    deleteCombo: 'Delete combo',
    editCombo: 'Edit combo',
    confirmDeleteCombo: 'Are you sure you want to delete this custom combo?',
    editComboName: 'Enter new combo name:',

    // Edit mode
    addEngine: 'Add engine',
    editEngine: 'Edit engine',
    deleteEngine: 'Delete engine',
    engineName: 'Engine name',
    searchUrl: 'Search URL',
    urlPlaceholder: 'Must contain %s',
    logoAutoUpdate: 'Logo will be updated automatically based on URL',
    cancel: 'Cancel',
    save: 'Save',
    confirmDelete: 'Are you sure you want to delete this engine?',

    // Footer
    footer: 'Press <kbd>Alt+S</kbd> to open • <kbd>Alt+Q</kbd> to search selected text',

    // Messages
    noEnginesSelected: 'Please select at least one search engine',
    maxCustomCombos: 'You can only save 5 custom combos. Please delete one first.',
    enterComboName: 'Enter combo name:',
    urlMustContainPlaceholder: 'URL must contain %s placeholder',
    defaultEngineCannotEdit: 'Default engines cannot be edited directly. Would you like to create a custom copy?',
    urlFormatError: 'URL format is incorrect, please check',
    enterEngineName: 'Engine name:',
    enterSearchUrl: 'Search URL (must contain %s):',
    enterDescription: 'Description:',
    pleaseEnterQuery: 'Please enter a search query',
    pleaseSelectEngines: 'Please select at least one search engine',

    // Edit engine modal
    editEngineTitle: 'Edit Engine',

    // Add engine
    addEngineTitle: 'Add Engine',
    addCustomEngine: 'Add Custom Engine',
    enterEngineNamePrompt: 'Engine name:',
    enterSearchUrlPrompt: 'Search URL (must contain %s):',
    urlFormatIncorrect: 'URL format is incorrect',
    pleaseEnterEngineName: 'Please enter an engine name',
    urlMustContainPlaceholder: 'URL must contain %s placeholder',
    invalidUrlFormat: 'Invalid URL format. Please check and try again.',
    pleaseEnterComboName: 'Please enter combo name',
    descriptionOptional: 'Description (optional)',
    logoAutoGenerated: 'Logo will be automatically generated from the URL',
    exampleGoogle: 'e.g., Google',
    examplePopularSearch: 'e.g., Popular search engine',
    exampleUrl: 'https://www.google.com/search?q=%s',

    // Language names
    languageEnglish: 'English',
    languageChinese: '中文',
    verticalTabs: 'Vertical Tabs',
    collapseAll: 'Collapse All Groups',
    refresh: 'Refresh',
    openSearchHubBtn: 'Open SearchHub',
    latestPrefix: 'Latest:',
    noTabs: 'No tabs yet',
    openSomeTabs: 'Open some tabs to see them here',
    otherTabs: 'Other Tabs',
    untitledGroup: 'Untitled Group',
    tabsWord: 'tabs',
    closeTab: 'Close tab',
    ungroup: 'Ungroup'
  },

  zh: {
    // Header
    title: 'SearchHub',
    themeToggle: '切换主题',
    compactMode: '紧凑模式',
    editMode: '编辑模式',
    settings: '设置',

    // Search
    searchPlaceholder: '在所有引擎中搜索...',
    search: '搜索',
    enginesSelected: '个引擎已选择',

    // Categories
    engines: '个引擎',
    expand: '展开',
    collapse: '折叠',
    selectAll: '选择该类目下所有引擎',

    // Combos
    saveAsCombo: '保存为组合',
    deleteCombo: '删除组合',
    editCombo: '编辑组合',
    confirmDeleteCombo: '确定要删除这个自定义组合吗？',
    editComboName: '请输入新的组合名称：',

    // Edit mode
    addEngine: '添加引擎',
    editEngine: '编辑引擎',
    deleteEngine: '删除引擎',
    engineName: '引擎名称',
    searchUrl: '搜索URL',
    urlPlaceholder: '必须包含 %s',
    logoAutoUpdate: 'Logo会根据URL自动更新',
    cancel: '取消',
    save: '保存',
    confirmDelete: '确定要删除这个引擎吗？',

    // Footer
    footer: '按 <kbd>Alt+S</kbd> 打开 • <kbd>Alt+Q</kbd> 搜索选中文字',

    // Messages
    noEnginesSelected: '请先选择至少一个搜索引擎',
    maxCustomCombos: '最多只能保存5个自定义组合，请先删除一个',
    enterComboName: '请输入组合名称：',
    urlMustContainPlaceholder: 'URL必须包含 %s 占位符',
    defaultEngineCannotEdit: '默认引擎不能直接编辑。是否创建自定义副本？',
    urlFormatError: 'URL格式不正确，请检查',
    enterEngineName: '引擎名称：',
    enterSearchUrl: '搜索URL（必须包含 %s）：',
    enterDescription: '描述：',
    pleaseEnterQuery: '请输入搜索关键词',
    pleaseSelectEngines: '请至少选择一个搜索引擎',

    // Edit engine modal
    editEngineTitle: '编辑引擎',

    // Add engine
    addEngineTitle: '添加引擎',
    addCustomEngine: '添加自定义引擎',
    enterEngineNamePrompt: '引擎名称：',
    enterSearchUrlPrompt: '搜索URL（必须包含 %s）：',
    urlFormatIncorrect: 'URL格式不正确',
    pleaseEnterEngineName: '请输入引擎名称',
    urlMustContainPlaceholder: 'URL必须包含 %s 占位符',
    invalidUrlFormat: 'URL格式无效，请检查后重试',
    pleaseEnterComboName: '请输入组合名称',
    descriptionOptional: '描述（可选）',
    logoAutoGenerated: 'Logo将根据URL自动生成',
    exampleGoogle: '例如：Google',
    examplePopularSearch: '例如：流行的搜索引擎',
    exampleUrl: 'https://www.google.com/search?q=%s',

    // Language names
    languageEnglish: 'English',
    languageChinese: '中文',
    verticalTabs: '垂直标签页',
    collapseAll: '全部折叠',
    refresh: '刷新',
    openSearchHubBtn: '打开 SearchHub',
    latestPrefix: '最近：',
    noTabs: '当前窗口没有标签页',
    openSomeTabs: '打开一些标签页后将在此显示',
    otherTabs: '未分组标签',
    untitledGroup: '未命名分组',
    tabsWord: '个标签页',
    closeTab: '关闭标签',
    ungroup: '取消分组'
  }
};

// Get current language (async version that uses chrome.storage)
async function getCurrentLanguageAsync() {
  try {
    // First try to get from chrome.storage.sync
    const result = await chrome.storage.sync.get(['settings']);
    if (result.settings?.language) {
      const lang = result.settings.language;
      if (lang === 'auto') {
        const browserLang = navigator.language || navigator.userLanguage;
        return browserLang.startsWith('zh') ? 'zh' : 'en';
      }
      return lang === 'zh' ? 'zh' : 'en';
    }
  } catch (error) {
    console.error('Failed to load language setting:', error);
  }
  
  // Fallback to localStorage (for backward compatibility)
  const stored = localStorage.getItem('searchhub_lang');
  if (stored === 'zh' || stored === 'en') return stored;
  
  // Fallback to state (if available)
  if (typeof state !== 'undefined' && state?.settings?.language) {
    const lang = state.settings.language;
    if (lang === 'auto') {
      const browserLang = navigator.language || navigator.userLanguage;
      return browserLang.startsWith('zh') ? 'zh' : 'en';
    }
    return lang === 'zh' ? 'zh' : 'en';
  }
  
  // Final fallback to browser language
  const browserLang = navigator.language || navigator.userLanguage;
  return browserLang.startsWith('zh') ? 'zh' : 'en';
}

// Get current language (synchronous version for backward compatibility)
function getCurrentLanguage() {
  // Try localStorage first (for immediate access)
  const stored = localStorage.getItem('searchhub_lang');
  if (stored === 'zh' || stored === 'en') return stored;
  
  // Try state if available
  if (typeof state !== 'undefined' && state?.settings?.language) {
    const lang = state.settings.language;
    if (lang === 'auto') {
      const browserLang = navigator.language || navigator.userLanguage;
      return browserLang.startsWith('zh') ? 'zh' : 'en';
    }
    return lang === 'zh' ? 'zh' : 'en';
  }
  
  // Fallback to browser language
  const browserLang = navigator.language || navigator.userLanguage;
  return browserLang.startsWith('zh') ? 'zh' : 'en';
}

// Get translated text
function t(key) {
  const lang = getCurrentLanguage();
  const translations = i18n[lang] || i18n.en;
  return translations[key] || key;
}

// Check if current language is Chinese
function isChineseLanguage() {
  return getCurrentLanguage() === 'zh';
}

// Update UI language
function updateUILanguage() {
  const lang = getCurrentLanguage();

  // Update search placeholder
  const searchInput = document.getElementById('searchInput');
  if (searchInput) {
    searchInput.placeholder = t('searchPlaceholder');
  }

  // Update search button
  const searchBtn = document.getElementById('searchBtn');
  if (searchBtn) {
    const span = searchBtn.querySelector('span');
    if (span) span.textContent = t('search');
  }

  // Update selected count (will be called by updateSelectedCount)

  // Update button titles
  const themeToggle = document.getElementById('themeToggle');
  if (themeToggle) themeToggle.title = t('themeToggle');

  const compactModeBtn = document.getElementById('compactModeBtn');
  if (compactModeBtn) compactModeBtn.title = t('compactMode');

  const editModeBtn = document.getElementById('editModeBtn');
  if (editModeBtn) editModeBtn.title = t('editMode');

  const settingsBtn = document.getElementById('settingsBtn');
  if (settingsBtn) settingsBtn.title = t('settings');

  // Update footer
  const footer = document.querySelector('.footer p');
  if (footer) {
    footer.innerHTML = t('footer');
  }

  // Update category headers
  document.querySelectorAll('.category-toggle').forEach(btn => {
    const grid = btn.closest('.category-header').nextElementSibling;
    if (grid) {
      const isCollapsed = grid.classList.contains('collapsed');
      btn.title = isCollapsed ? t('expand') : t('collapse');
    }
  });

  // Update data-i18n elements (for Chrome Extension i18n API support)
  document.querySelectorAll('[data-i18n]').forEach(element => {
    const key = element.getAttribute('data-i18n');
    const translatedText = t(key);
    if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
      if (element.type === 'button' || element.type === 'submit') {
        element.value = translatedText;
      }
    } else {
      element.textContent = translatedText;
    }
  });

  // Update data-i18n-placeholder elements
  document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
    const key = element.getAttribute('data-i18n-placeholder');
    element.placeholder = t(key);
  });

  // Update data-i18n-title elements
  document.querySelectorAll('[data-i18n-title]').forEach(element => {
    const key = element.getAttribute('data-i18n-title');
    element.title = t(key);
  });
}

// Toggle language between English and Chinese
async function toggleLanguage() {
  if (typeof state !== 'undefined' && state.settings) {
    const currentLang = getCurrentLanguage();
    const newLang = currentLang === 'en' ? 'zh' : 'en';
    state.settings.language = newLang;

    // Save to chrome.storage.sync (primary)
    try {
      if (typeof saveSettings === 'function') {
        await saveSettings();
      } else {
        // If saveSettings doesn't exist, save directly
        await chrome.storage.sync.set({ settings: state.settings });
      }
    } catch (error) {
      console.error('Failed to save language setting:', error);
    }

    // Also save to localStorage for backward compatibility
    localStorage.setItem('searchhub_lang', newLang);

    // Update UI
    updateUILanguage();

    // Update selected count if function exists
    if (typeof updateSelectedCount === 'function') {
      updateSelectedCount();
    }

    // Re-render categories to update engine count text
    if (typeof renderCategories === 'function') {
      const selectedBefore = new Set(state.selectedEngines);
      renderCategories();
      state.selectedEngines = selectedBefore;
      // Re-apply selected state
      selectedBefore.forEach(engineId => {
        const card = document.querySelector(`[data-engine-id="${engineId}"]`);
        if (card) card.classList.add('selected');
      });
      updateSelectedCount();
    }
  }
}

