// Internationalization (i18n) support

const i18n = {
  en: {
    title: 'SearchHub',
    themeToggle: 'Toggle theme',
    compactMode: 'Compact mode',
    editMode: 'Edit mode',
    settings: 'Settings',
    searchPlaceholder: 'Search anything across all engines...',
    search: 'Search',
    enginesSelected: 'engines selected',
    engines: 'engines',
    expand: 'Expand',
    collapse: 'Collapse',
    selectAll: 'Select all engines in this category',
    saveAsCombo: 'Save as combo',
    deleteCombo: 'Delete combo',
    editCombo: 'Edit combo',
    confirmDeleteCombo: 'Are you sure you want to delete this custom combo?',
    editComboName: 'Enter new combo name:',
    addEngine: 'Add engine',
    editEngine: 'Edit engine',
    deleteEngine: 'Delete engine',
    engineName: 'Engine name',
    searchUrl: 'Search URL',
    urlPlaceholder: 'Must contain %s',
    logoAutoUpdate: 'Logo will be updated automatically based on URL',
    cancel: 'Cancel',
    save: 'Save',
    confirmDelete: 'Are you sure you want to delete this engine?',
    footer: 'Press <kbd>Alt+S</kbd> to open • <kbd>Alt+Q</kbd> to search selected text',
    noEnginesSelected: 'Please select at least one search engine',
    maxCustomCombos: 'You can only save 5 custom combos. Please delete one first.',
    enterComboName: 'Enter combo name:',
    urlMustContainPlaceholder: 'URL must contain %s placeholder',
    defaultEngineCannotEdit: 'Default engines cannot be edited directly. Would you like to create a custom copy?',
    urlFormatError: 'URL format is incorrect, please check',
    enterEngineName: 'Engine name:',
    enterSearchUrl: 'Search URL (must contain %s):',
    enterDescription: 'Description:',
    pleaseEnterQuery: 'Please enter a search query',
    pleaseSelectEngines: 'Please select at least one search engine',
    editEngineTitle: 'Edit Engine',
    addEngineTitle: 'Add Engine',
    addCustomEngine: 'Add Custom Engine',
    enterEngineNamePrompt: 'Engine name:',
    enterSearchUrlPrompt: 'Search URL (must contain %s):',
    urlFormatIncorrect: 'URL format is incorrect',
    pleaseEnterEngineName: 'Please enter an engine name',
    invalidUrlFormat: 'Invalid URL format. Please check and try again.',
    pleaseEnterComboName: 'Please enter combo name',
    descriptionOptional: 'Description (optional)',
    logoAutoGenerated: 'Logo will be automatically generated from the URL',
    exampleGoogle: 'e.g., Google',
    examplePopularSearch: 'e.g., Popular search engine',
    exampleUrl: 'https://www.google.com/search?q=%s',
    language: 'Language',
    verticalTabs: 'Vertical Tabs',
    collapseAll: 'Collapse All Groups',
    refresh: 'Refresh',
    openSearchHubBtn: 'Open SearchHub',
    latestPrefix: 'Latest:',
    noTabs: 'No tabs yet',
    openSomeTabs: 'Open some tabs to see them here',
    otherTabs: 'Other Tabs',
    untitledGroup: 'Untitled Group',
    tabsWord: 'tabs',
    closeTab: 'Close tab',
    ungroup: 'Ungroup'
  },

  zh: {
    title: 'SearchHub',
    themeToggle: '切换主题',
    compactMode: '紧凑模式',
    editMode: '编辑模式',
    settings: '设置',
    searchPlaceholder: '在所有引擎中搜索...',
    search: '搜索',
    enginesSelected: '个引擎已选择',
    engines: '个引擎',
    expand: '展开',
    collapse: '折叠',
    selectAll: '选择该类目下所有引擎',
    saveAsCombo: '保存为组合',
    deleteCombo: '删除组合',
    editCombo: '编辑组合',
    confirmDeleteCombo: '确定要删除这个自定义组合吗？',
    editComboName: '请输入新的组合名称：',
    addEngine: '添加引擎',
    editEngine: '编辑引擎',
    deleteEngine: '删除引擎',
    engineName: '引擎名称',
    searchUrl: '搜索URL',
    urlPlaceholder: '必须包含 %s',
    logoAutoUpdate: 'Logo会根据URL自动更新',
    cancel: '取消',
    save: '保存',
    confirmDelete: '确定要删除这个引擎吗？',
    footer: '按 <kbd>Alt+S</kbd> 打开 • <kbd>Alt+Q</kbd> 搜索选中文字',
    noEnginesSelected: '请先选择至少一个搜索引擎',
    maxCustomCombos: '最多只能保存5个自定义组合，请先删除一个',
    enterComboName: '请输入组合名称：',
    urlMustContainPlaceholder: 'URL必须包含 %s 占位符',
    defaultEngineCannotEdit: '默认引擎不能直接编辑。是否创建自定义副本？',
    urlFormatError: 'URL格式不正确，请检查',
    enterEngineName: '引擎名称：',
    enterSearchUrl: '搜索URL（必须包含 %s）：',
    enterDescription: '描述：',
    pleaseEnterQuery: '请输入搜索关键词',
    pleaseSelectEngines: '请至少选择一个搜索引擎',
    editEngineTitle: '编辑引擎',
    addEngineTitle: '添加引擎',
    addCustomEngine: '添加自定义引擎',
    enterEngineNamePrompt: '引擎名称：',
    enterSearchUrlPrompt: '搜索URL（必须包含 %s）：',
    urlFormatIncorrect: 'URL格式不正确',
    pleaseEnterEngineName: '请输入引擎名称',
    invalidUrlFormat: 'URL格式无效，请检查后重试',
    pleaseEnterComboName: '请输入组合名称',
    descriptionOptional: '描述（可选）',
    logoAutoGenerated: 'Logo将根据URL自动生成',
    exampleGoogle: '例如：Google',
    examplePopularSearch: '例如：流行的搜索引擎',
    exampleUrl: 'https://www.google.com/search?q=%s',
    language: '语言',
    verticalTabs: '垂直标签页',
    collapseAll: '全部折叠',
    refresh: '刷新',
    openSearchHubBtn: '打开 SearchHub',
    latestPrefix: '最近：',
    noTabs: '当前窗口没有标签页',
    openSomeTabs: '打开一些标签页后将在此显示',
    otherTabs: '未分组标签',
    untitledGroup: '未命名分组',
    tabsWord: '个标签页',
    closeTab: '关闭标签',
    ungroup: '取消分组'
  },

  es: {
    title: 'SearchHub',
    themeToggle: 'Cambiar tema',
    compactMode: 'Modo compacto',
    editMode: 'Modo edición',
    settings: 'Ajustes',
    searchPlaceholder: 'Busca en todos los motores...',
    search: 'Buscar',
    enginesSelected: 'motores seleccionados',
    engines: 'motores',
    expand: 'Expandir',
    collapse: 'Contraer',
    selectAll: 'Seleccionar todos los motores de esta categoría',
    saveAsCombo: 'Guardar como combo',
    deleteCombo: 'Eliminar combo',
    editCombo: 'Editar combo',
    confirmDeleteCombo: '¿Seguro que quieres eliminar este combo?',
    editComboName: 'Introduce el nuevo nombre del combo:',
    addEngine: 'Añadir motor',
    editEngine: 'Editar motor',
    deleteEngine: 'Eliminar motor',
    engineName: 'Nombre del motor',
    searchUrl: 'URL de búsqueda',
    urlPlaceholder: 'Debe contener %s',
    logoAutoUpdate: 'El logo se actualizará automáticamente según la URL',
    cancel: 'Cancelar',
    save: 'Guardar',
    confirmDelete: '¿Seguro que quieres eliminar este motor?',
    footer: 'Pulsa <kbd>Alt+S</kbd> para abrir • <kbd>Alt+Q</kbd> para buscar texto seleccionado',
    noEnginesSelected: 'Por favor selecciona al menos un motor de búsqueda',
    maxCustomCombos: 'Solo puedes guardar 5 combos. Elimina uno primero.',
    enterComboName: 'Nombre del combo:',
    urlMustContainPlaceholder: 'La URL debe contener el marcador %s',
    defaultEngineCannotEdit: 'Los motores predeterminados no se pueden editar directamente. ¿Crear una copia?',
    urlFormatError: 'Formato de URL incorrecto, compruébalo',
    enterEngineName: 'Nombre del motor:',
    enterSearchUrl: 'URL de búsqueda (debe contener %s):',
    enterDescription: 'Descripción:',
    pleaseEnterQuery: 'Por favor introduce un término de búsqueda',
    pleaseSelectEngines: 'Por favor selecciona al menos un motor de búsqueda',
    editEngineTitle: 'Editar motor',
    addEngineTitle: 'Añadir motor',
    addCustomEngine: 'Añadir motor personalizado',
    enterEngineNamePrompt: 'Nombre del motor:',
    enterSearchUrlPrompt: 'URL de búsqueda (debe contener %s):',
    urlFormatIncorrect: 'Formato de URL incorrecto',
    pleaseEnterEngineName: 'Por favor introduce el nombre del motor',
    invalidUrlFormat: 'Formato de URL no válido. Comprueba e inténtalo de nuevo.',
    pleaseEnterComboName: 'Por favor introduce el nombre del combo',
    descriptionOptional: 'Descripción (opcional)',
    logoAutoGenerated: 'El logo se generará automáticamente desde la URL',
    exampleGoogle: 'ej., Google',
    examplePopularSearch: 'ej., Motor de búsqueda popular',
    exampleUrl: 'https://www.google.com/search?q=%s',
    language: 'Idioma',
    verticalTabs: 'Pestañas verticales',
    collapseAll: 'Contraer todos los grupos',
    refresh: 'Actualizar',
    openSearchHubBtn: 'Abrir SearchHub',
    latestPrefix: 'Último:',
    noTabs: 'No hay pestañas',
    openSomeTabs: 'Abre pestañas para verlas aquí',
    otherTabs: 'Otras pestañas',
    untitledGroup: 'Grupo sin título',
    tabsWord: 'pestañas',
    closeTab: 'Cerrar pestaña',
    ungroup: 'Desagrupar'
  },

  fr: {
    title: 'SearchHub',
    themeToggle: 'Changer le thème',
    compactMode: 'Mode compact',
    editMode: 'Mode édition',
    settings: 'Paramètres',
    searchPlaceholder: 'Recherchez sur tous les moteurs...',
    search: 'Rechercher',
    enginesSelected: 'moteurs sélectionnés',
    engines: 'moteurs',
    expand: 'Développer',
    collapse: 'Réduire',
    selectAll: 'Sélectionner tous les moteurs de cette catégorie',
    saveAsCombo: 'Enregistrer comme combo',
    deleteCombo: 'Supprimer le combo',
    editCombo: 'Modifier le combo',
    confirmDeleteCombo: 'Voulez-vous vraiment supprimer ce combo ?',
    editComboName: 'Entrez le nouveau nom du combo :',
    addEngine: 'Ajouter un moteur',
    editEngine: 'Modifier le moteur',
    deleteEngine: 'Supprimer le moteur',
    engineName: 'Nom du moteur',
    searchUrl: 'URL de recherche',
    urlPlaceholder: 'Doit contenir %s',
    logoAutoUpdate: 'Le logo sera mis à jour automatiquement selon l\'URL',
    cancel: 'Annuler',
    save: 'Enregistrer',
    confirmDelete: 'Voulez-vous vraiment supprimer ce moteur ?',
    footer: 'Appuyez sur <kbd>Alt+S</kbd> pour ouvrir • <kbd>Alt+Q</kbd> pour rechercher le texte sélectionné',
    noEnginesSelected: 'Veuillez sélectionner au moins un moteur de recherche',
    maxCustomCombos: 'Vous ne pouvez enregistrer que 5 combos. Supprimez-en un d\'abord.',
    enterComboName: 'Nom du combo :',
    urlMustContainPlaceholder: 'L\'URL doit contenir l\'espace réservé %s',
    defaultEngineCannotEdit: 'Les moteurs par défaut ne peuvent pas être modifiés directement. Créer une copie ?',
    urlFormatError: 'Format d\'URL incorrect, vérifiez',
    enterEngineName: 'Nom du moteur :',
    enterSearchUrl: 'URL de recherche (doit contenir %s) :',
    enterDescription: 'Description :',
    pleaseEnterQuery: 'Veuillez entrer un terme de recherche',
    pleaseSelectEngines: 'Veuillez sélectionner au moins un moteur de recherche',
    editEngineTitle: 'Modifier le moteur',
    addEngineTitle: 'Ajouter un moteur',
    addCustomEngine: 'Ajouter un moteur personnalisé',
    enterEngineNamePrompt: 'Nom du moteur :',
    enterSearchUrlPrompt: 'URL de recherche (doit contenir %s) :',
    urlFormatIncorrect: 'Format d\'URL incorrect',
    pleaseEnterEngineName: 'Veuillez entrer le nom du moteur',
    invalidUrlFormat: 'Format d\'URL invalide. Vérifiez et réessayez.',
    pleaseEnterComboName: 'Veuillez entrer le nom du combo',
    descriptionOptional: 'Description (optionnelle)',
    logoAutoGenerated: 'Le logo sera généré automatiquement depuis l\'URL',
    exampleGoogle: 'ex., Google',
    examplePopularSearch: 'ex., Moteur de recherche populaire',
    exampleUrl: 'https://www.google.com/search?q=%s',
    language: 'Langue',
    verticalTabs: 'Onglets verticaux',
    collapseAll: 'Réduire tous les groupes',
    refresh: 'Actualiser',
    openSearchHubBtn: 'Ouvrir SearchHub',
    latestPrefix: 'Dernier :',
    noTabs: 'Aucun onglet',
    openSomeTabs: 'Ouvrez des onglets pour les voir ici',
    otherTabs: 'Autres onglets',
    untitledGroup: 'Groupe sans titre',
    tabsWord: 'onglets',
    closeTab: 'Fermer l\'onglet',
    ungroup: 'Dégrouper'
  }
};

const SUPPORTED_LANGS = ['en', 'zh', 'es', 'fr'];

// Resolve a raw lang string to a supported code
function resolveLang(lang) {
  if (!lang || lang === 'auto') {
    const bl = (navigator.language || '').toLowerCase();
    if (bl.startsWith('zh')) return 'zh';
    if (bl.startsWith('es')) return 'es';
    if (bl.startsWith('fr')) return 'fr';
    return 'en';
  }
  return SUPPORTED_LANGS.includes(lang) ? lang : 'en';
}

// In-memory cache — populated on first async load, updated on toggle
let _cachedLang = null;

// Async load from chrome.storage (call once on page init)
async function initLanguage() {
  try {
    const result = await chrome.storage.sync.get(['settings']);
    _cachedLang = resolveLang(result.settings?.language);
  } catch (e) {
    _cachedLang = resolveLang(null);
  }
  return _cachedLang;
}

// Synchronous read — uses cache; falls back to browser lang before cache is ready
function getCurrentLanguage() {
  if (_cachedLang) return _cachedLang;
  // Pre-cache fallback: read from state if index.js already loaded settings
  if (typeof state !== 'undefined' && state?.settings?.language) {
    return resolveLang(state.settings.language);
  }
  return resolveLang(null);
}

// Get translated text
function t(key) {
  const lang = getCurrentLanguage();
  return (i18n[lang] || i18n.en)[key] || (i18n.en)[key] || key;
}

// Update all translatable elements in the current page
function updateUILanguage() {
  const searchInput = document.getElementById('searchInput');
  if (searchInput) searchInput.placeholder = t('searchPlaceholder');

  const searchBtn = document.getElementById('searchBtn');
  if (searchBtn) {
    const span = searchBtn.querySelector('span');
    if (span) span.textContent = t('search');
  }

  const themeToggle = document.getElementById('themeToggle');
  if (themeToggle) themeToggle.title = t('themeToggle');

  const compactModeBtn = document.getElementById('compactModeBtn');
  if (compactModeBtn) compactModeBtn.title = t('compactMode');

  const editModeBtn = document.getElementById('editModeBtn');
  if (editModeBtn) editModeBtn.title = t('editMode');

  const settingsBtn = document.getElementById('settingsBtn');
  if (settingsBtn) settingsBtn.title = t('settings');

  const footer = document.querySelector('.footer p');
  if (footer) footer.innerHTML = t('footer');

  document.querySelectorAll('.category-toggle').forEach(btn => {
    const grid = btn.closest('.category-header')?.nextElementSibling;
    if (grid) btn.title = grid.classList.contains('collapsed') ? t('expand') : t('collapse');
  });

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (el.tagName === 'INPUT' && (el.type === 'button' || el.type === 'submit')) {
      el.value = t(key);
    } else {
      el.textContent = t(key);
    }
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
  });

  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    el.title = t(el.getAttribute('data-i18n-title'));
  });

  // Update language button label
  const langText = document.getElementById('langText');
  if (langText) {
    const labels = { en: 'EN', zh: '中', es: 'ES', fr: 'FR' };
    langText.textContent = labels[getCurrentLanguage()] || 'EN';
  }
}

// Cycle through languages: en → zh → es → fr → en
async function toggleLanguage() {
  const current = getCurrentLanguage();
  const idx = SUPPORTED_LANGS.indexOf(current);
  const next = SUPPORTED_LANGS[(idx + 1) % SUPPORTED_LANGS.length];

  _cachedLang = next;

  // Persist to chrome.storage.sync
  try {
    if (typeof state !== 'undefined' && state.settings) {
      state.settings.language = next;
      if (typeof saveSettings === 'function') {
        await saveSettings();
      } else {
        await chrome.storage.sync.set({ settings: state.settings });
      }
    } else {
      // settings page context
      const result = await chrome.storage.sync.get(['settings']);
      const s = result.settings || {};
      s.language = next;
      await chrome.storage.sync.set({ settings: s });
    }
  } catch (e) {
    console.error('Failed to save language:', e);
  }

  // Broadcast to all extension pages so they update without refresh
  try {
    chrome.runtime.sendMessage({ action: 'languageChanged', lang: next });
  } catch (e) { /* ignore if no listeners */ }

  updateUILanguage();

  if (typeof updateSelectedCount === 'function') updateSelectedCount();

  if (typeof renderCategories === 'function') {
    const selectedBefore = new Set(state.selectedEngines);
    renderCategories();
    state.selectedEngines = selectedBefore;
    selectedBefore.forEach(id => {
      const card = document.querySelector(`[data-engine-id="${id}"]`);
      if (card) card.classList.add('selected');
    });
    updateSelectedCount();
  }
}

// Listen for language change broadcast from other pages
chrome.runtime.onMessage.addListener((message) => {
  if (message.action === 'languageChanged') {
    _cachedLang = message.lang;
    updateUILanguage();
    if (typeof updateSelectedCount === 'function') updateSelectedCount();
    if (typeof renderCategories === 'function') {
      const selectedBefore = new Set(state?.selectedEngines || []);
      renderCategories();
      state.selectedEngines = selectedBefore;
      selectedBefore.forEach(id => {
        const card = document.querySelector(`[data-engine-id="${id}"]`);
        if (card) card.classList.add('selected');
      });
      updateSelectedCount();
    }
  }
});
